@baseURL = http://localhost:8080

### Register new user

POST {{baseURL}}/api/register
Content-Type: application/json

{
    "name": "test",
    "email": "steve@pm.com",
    "password": "steve_boladão"
}