@baseURL = http://localhost:8080

### Register new user

POST {{baseURL}}/api/register
Content-Type: application/json

{
    "name": "CJ",
    "email": "carl@jonhsson.com",
    "password": "grove_stret"
}