### List all users
GET {{baseURL}}/api/user

### List user by ID
GET {{baseURL}}/api/user/7

### Register new user
POST {{baseURL}}/api/user
Content-Type: application/json

{
    "name": "Maad dog",
    "email": "mad@dog.com",
    "password": "hiphop"
}

### Update user
PUT {{baseURL}}/api/user/8
Content-Type: application/json

{
    "email": "big@jonhsson.com"
}

### Delete user
DELETE {{baseURL}}/api/user/8
